sonar.projectKey=create-react-renderer
sonar.sources=.
sonar.exclusions=slides/**,assets/**
sonar.test.inclusions=**/tests/**,**/*.spec.tsx
sonar.javascript.lcov.reportPaths=phase*/coverage/lcov.info
sonar.typescript.lcov.reportPaths=phase*/coverage/lcov.info
